environment_version: "2"
dependencies:
  - torch
  - transformers
  - sentencepiece
  - langchain
  - langchain-community==0.3.18
  - langchain_text_splitters
  - langchain-experimental
  - langchain-huggingface
  - langchain-openai
  - langgraph
  - grandalf
  - sentence-transformers
  - pymilvus
  - langchain-milvus
  - langchain-chroma
  - pydantic
  - beautifulsoup4
  - pypdf
  - duckduckgo-search

